// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKSAci4faoKbttv_91RCVP1svBrrlJQ3A',
    appId: '1:679131789754:web:89ffefcfb17c0856af4583',
    messagingSenderId: '679131789754',
    projectId: 'ams-mims',
    authDomain: 'ams-mims.firebaseapp.com',
    storageBucket: 'ams-mims.firebasestorage.app',
    measurementId: 'G-9ZZH7G3112',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHBuXfHiQEdHkGz23lFD_mzNRsyQK7TAQ',
    appId: '1:679131789754:android:ae62f9fc9620f900af4583',
    messagingSenderId: '679131789754',
    projectId: 'ams-mims',
    storageBucket: 'ams-mims.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA3a4Qq4kr3_m3Clpr3ayok4epbILUicI',
    appId: '1:679131789754:ios:34b25a52527380a5af4583',
    messagingSenderId: '679131789754',
    projectId: 'ams-mims',
    storageBucket: 'ams-mims.firebasestorage.app',
    iosBundleId: 'com.example.amsMims',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA3a4Qq4kr3_m3Clpr3ayok4epbILUicI',
    appId: '1:679131789754:ios:34b25a52527380a5af4583',
    messagingSenderId: '679131789754',
    projectId: 'ams-mims',
    storageBucket: 'ams-mims.firebasestorage.app',
    iosBundleId: 'com.example.amsMims',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKSAci4faoKbttv_91RCVP1svBrrlJQ3A',
    appId: '1:679131789754:web:63aa6295b0c5d0acaf4583',
    messagingSenderId: '679131789754',
    projectId: 'ams-mims',
    authDomain: 'ams-mims.firebaseapp.com',
    storageBucket: 'ams-mims.firebasestorage.app',
    measurementId: 'G-HXV4ER2W6Y',
  );

}